service:
  name: cucumber-chrome-aws

provider:
  name: aws
  runtime: java8
  region: us-east-1
  iamRoleStatements:
  - Effect: Allow
    Resource: "*"
    Action:
    - ses:SendEmail

package:
  artifact: target/webdrivertraining-1.0-SNAPSHOT.jar

functions:
  runCucumber:
    handler: com.octopus.LambdaEntry::runCucumber
    timeout: 300
    memorySize: 512
    events:
    - http:
        method: post
        path: runCucumber
        integration: lambda
        request:
          parameters:
            headers:
              'X-Amz-Invocation-Type': true
          template:
            text/plain: "\"$util.escapeJavaScript($input.body).replaceAll(\"\\'\",\"'\")\""
        response:
          headers:
            Content-Type: "'application/json'"
          template: $util.parseJson($input.body)